---
title: "ToDo"
---

- [hoxo_mがいいねした記事 - Qiita](https://qiita.com/hoxo_m/like)
- [yuifu/ajacs68: Materials for tutorial at ajacs68 (Japanese)](https://github.com/yuifu/ajacs68)
- [臨床心理学におけるR入門: データハンドリングから統計解析まで](https://www.slideshare.net/YoshihikoKunisato/r-74207682)
- [Overleaf v2 で日本語を使用する方法 - TeX Alchemist Online](http://doratex.hatenablog.jp/entry/20180503/1525338512)
- [Presentations by kilometer - Speaker Deck](https://speakerdeck.com/kilometer)
- [ggplot2で臨床経過図を、簡単に作成する - Ｒ言語による電子カルテデータの二次利用](http://r-beginner.hatenadiary.jp/entry/2018/06/23/155503)

## ダイアグラム

- [Graphviz で CONSORT 的な RCT 用 flowchart 作成 - Qiita](https://qiita.com/babayoshihiko/items/1feec876352c5870260a)
- [DiagrammeR　〜RでGraphvizを使う~ - Ｒ言語による電子カルテデータの二次利用](http://r-beginner.hatenadiary.jp/entry/2018/03/11/081150)


## 機械学習

- [christophM/interpretable-ml-book: Book about interpretable machine learning](https://github.com/christophM/interpretable-ml-book)
- [画像処理100本ノックを作ったった - Qiita](https://qiita.com/yoyoyo_/items/2ef53f47f87dcf5d1e14)

## 並列化

- [【超訳】foreach パッケージの使い方 #rstatsj - Qiita](https://qiita.com/hoxo_m/items/04903cbbe9d023f0ed6d)

## 統計

- [心理学者のためのベイズ統計入門 | Sunny side up!](http://norimune.net/2740)
- [JIN'S PAGE](https://mjin.doshisha.ac.jp/R/)

- [Mathematical Foundation of Statistical Learning](http://watanabe-www.math.dis.titech.ac.jp/users/swatanab/joho05.pdf)
- [Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/)
- [Computer Age Statistical Inference: Algorithms, Evidence and Data Science](https://web.stanford.edu/~hastie/CASI/)
- [Statistical Learning with Sparsity: the Lasso and Generalizations](https://web.stanford.edu/~hastie/StatLearnSparsity/)

### 数学的に……

- [黒木玄のウェブサイト](https://genkuroki.github.io/)
- [黒木玄先生の統計の話（など） - Togetter](https://togetter.com/li/1213644)
- [Jupyter Notebook Viewer](https://nbviewer.jupyter.org/gist/genkuroki/)
- [混合正規分布モデルと正規分布モデルの各種情報量規準の比較](https://nbviewer.jupyter.org/gist/genkuroki/d688c6e5e8c427dba9856d37a12bbee1)
- [黒木玄 Gen Kurokiさんのツイート: "例えば、多くの教科書に、2×2の分割表の独立性検定(よく使われる標準的な道具)について、 Fisherの正確確率検定はp値を正確に計算できる。(Pearsonの)カイ二乗検定はその近似に過ぎない。両方使えるなら前者を使うべきである。 のように書いてあります。しかし、これは単純に誤り。#統計"](https://twitter.com/genkuroki/status/1081065881889730561)
- [黒木玄 Gen Kurokiさんのツイート: "#数楽 真の分布q(y)を最もよくシミュレートするp(y|w)型の分布の例について これは正確には、KL情報量D(w)=∫q(y) log(q(y)/p(y|w)) dyを最小にするw=w₀に対するp(y|w₀)のことです。 KL情報量がこういう意味を持つという結果はSanovの定理と呼ばれています。 https://t.co/uzZ6l8t902"](https://twitter.com/genkuroki/status/1079522710781276160)
- [黒木玄 Gen Kurokiさんのツイート: "https://t.co/wDYCFLrd9h を読みました。 そこで引用されている https://t.co/raWipVBSzj から始まるスレッドの重要なキーワードは【未知の確率分布の推定】です。i.i.d.を仮定しない一般的な場合には、確率的法則の推定と言った方がよいかもしれません。続く… https://t.co/sLsrTfbkpO"](https://twitter.com/genkuroki/status/1079497388165783552)
- [黒木玄 Gen Kurokiさんのツイート: "統計学のための数学的素養としては、 * 大数の(弱)法則 * 中心極限定理 * Kullback-Leibler情報量に関するSanovの定理 あたりが基本的なのですが、私が書いた(謙遜ではなくあまりよくなさそうな)解説が以下の場所にあります。 https://t.co/taC7B39G3k https://t.co/wSDIgaOAqf… https://t.co/cJh7Kink4C"](https://twitter.com/genkuroki/status/1087287538996281345?s=12)
- [黒木玄 Gen Kurokiさんのツイート: "#統計 赤池さんの1980年の論説は次の場所で読めます。 https://t.co/YRhnSOzAll 統計的推論のパラダイムの変遷について(1980) 赤池弘次 こういう話を学生時代に聴きたかった。あと次も面白い。 https://t.co/0XWLnhwq6V"](https://twitter.com/genkuroki/status/971402131407126529)

- [Juliaで最尤推定：ポアソン回帰を例に - 廿TT](http://abrahamcow.hatenablog.com/entry/2019/01/03/201210)
- [Fourier Transforms](http://www.jezzamon.com/fourier/index.html)：フーリエ変換のアニメーション

## fzf

- [fzf（fuzzy finder）の便利な使い方をREADME, Wikiを読んで学ぶ - もた日記](https://wonderwall.hatenablog.com/entry/2017/10/06/063000)
- [fzfによるCUI生活の改善](https://blog.nijohando.jp/post/fzf-fish-vim/)

## ripgrep

- [.ripgreprc & glob patterns · Issue #927 · BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep/issues/927)
- [BurntSushi/ripgrep: ripgrep recursively searches directories for a regex pattern](https://github.com/BurntSushi/ripgrep)

## Alfred

- [Alfred WorkflowのScript Filterを利用して、共通の値をまとめる | 豆腐メンタルは崩れない](http://wbtmiu.herokuapp.com/2014/10/20/d99f603c029aa9fa19ff63582703265a/)
- [Alfred WorkflowのScript Filterを利用して、共通の値をまとめる〜シェルスクリプト編〜 | 豆腐メンタルは崩れない](https://wbtmiu.herokuapp.com/2014/10/22/5df13745be5c1915929f73c079a5ba81/)
